CREATE TABLE IF NOT EXISTS `gsc_admin_user` (
	`id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`username` VARCHAR(20) NOT NULL COMMENT '用户名',
	`password` VARCHAR(20) NOT NULL COMMENT '密码',
	`level` TINYINT(2) DEFAULT 0,
  `created_at` DATETIME COMMENT '创建时间',
  `updated_at` DATETIME COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
